config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'contacts/new'

  get 'contacts/create'

  get 'contacts/create'
  get 'contacts/new'
  #get 'home/gallery'
  
  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config
  root to: 'home#index'
  devise_for :users, controllers: {registrations: 'registrations'}
  resources "contacts", only: [:new, :create]
  resources :users do
    resources :galleries do
      collection do
        get :import_csv_form
        post :import
      end
    end
  end
  resources :users do
    resources :galleries do
      member do
        get :check_name
      end
    end
  end

  resources :galleries do
    collection do
      get :get_image_count
    end
  end
  
  namespace :api do
      namespace :v1 do
        resources :gallery_pictures, only: [] do
          collection do
            post :upload
          end
          member do
            get :retrieve
          end
        end
        resources :contacts, only: [] do
          collection do
            post :send_message
          end
        end
        resources :users, only: [] do
          collection do
            post :create_user
          end
        end
      end
  end

  match "*path", to: "api/v1/errors#routing", via: :all
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
end

app/models/gallery.rb
class Gallery < ApplicationRecord
  require 'csv'
  belongs_to :user
  validates :name, presence: true, uniqueness: true
  has_attached_file :image, styles: { small: "64x64", med: "100x100", large: "200x200" },
                            :url  => "/assets/products/:id/:style/:basename.:extension",
                            :path => ":rails_root/public/assets/products/:id/:style/:basename.:extension"
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
  paginates_per  2

  def self.import(file)
    @errors = []
    CSV.foreach(file.path, headers: true) do |row|
      Rails.logger.info("in for each")
      begin
        gallery = Gallery.new(row.to_hash)
        Rails.logger.info(gallery)
        if !gallery.save
          Rails.logger.info("NOT SAVED")
          gallery.errors.full_messages.each do |message|
           # Rails.logger.info(message)
            @errors << "#{message}"
            Rails.logger.info(@errors.inspect)
          end
        end
      rescue SocketError => details    # or the Exception class name may be SocketError  
        @errors << "Failed to load the data: #{details}"
        return @errors
      end
    end
    return @errors
  end
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  before_action :find_current_user
  before_action :find_gallery, only: [:edit, :update]
  require 'uri'


  def index
    @galleries = Kaminari.paginate_array(Rails.cache.fetch(:gallerylist, :expires_in =>  5.minutes) do
      @user.galleries.order('created_at DESC').to_a
    end).page(params[:page]).per(2)
  end

  def new
    @gallery = @user.galleries.build
    #Rails.logger.info("#{@gallery}")
    respond_to do |format|
      format.js
    end
  end

  def create
    @gallery = @user.galleries.build(gallery_params)
    if @gallery.save
      @galleries = @user.galleries.page(params[:page]).order('created_at DESC').per(2)
      respond_to do |format|
        format.js
      end
    else
      respond_to do |format|
        format.js { render 'new'}
      end
    end
  end


  def edit

  end

  def update
    if @gallery.update_attributes(gallery_params)
      respond_to do |format|
        format.js
      end
    else
      respond_to do |format|
        format.js { render 'edit'}
      end
    end
  end

  def check_name
      @gallery = @user.galleries.where('id != ?',params[:id]).where('name == ?',params[:gallery][:name]).first
    respond_to do |format|
      format.json { render json: !@gallery }
    end
  end


  def get_image_count
    sleep 3
    @gallery_count = @user.galleries.count
    render json: { data: @gallery_count}
  end

  def import_csv_form
    respond_to do |format|
      format.js
    end
  end

  def import
  # To validate headers in csv file
    @file = params[:file].path
    validate_header
    #validate data of csv if headers are valid
    @row = []
    @import_count = 0
    @failed_import = 0
    @failed_format = 0
    CSV.foreach(@file,encoding:'iso-8859-1:utf-8', col_sep: ';') do |row|
      @row << row
    end
    if @row.length > 1 && !@errors.any?# data exists more than header
      @row.each_with_index do |row, index|
        next if index == 0
        @errors = validate_csv_data(row,index)
        if !@errors.present?
          params = row.first.split(",")
          begin
            @gallery = @user.galleries.build(name: params[0], image: params[1])
          rescue
            
          end
          begin
            if @gallery.save
              @import_count += 1
            end
          rescue 
            Rails.logger.info("EXCEPTION")
            @failed_import += 1
          end
        else
          @failed_format +=1
        end
      end
    else
     @errors << "Content is missing"
    end
    if @errors.present?
      respond_to do |format|
        format.js
      end
    else
      if @import_count >= 1 && @failed_import >= 1 && @failed_format >= 1
        @msg = "#{@import_count} rows are imported sucessfully , #{@failed_import} rows could not be imported as the file is missing and #{@failed_format} rows could not be validated and imported"
      elsif @failed_import >= 1 && @import_count >= 1 && @failed_format == 0
        @msg = "#{@import_count} rows are imported sucessfully , #{@failed_import} rows could not be imported as the file is missing"
      elsif @import_count >= 1 && @failed_import == 0 && @failed_format == 0
        @msg = "#{@import_count} rows are imported sucessfully"
      end
      redirect_to user_galleries_url(@user), notice: "#{@msg}"
    end
  end

private

  def gallery_params
    params.require(:gallery).permit(
      :name, :image, :user_id
    )
  end

  def find_current_user
    @user = current_user
  end

  def find_gallery
    @gallery = @user.galleries.find_by(id: params[:id])
  end

  #validation of header in a csv file
  def validate_header
    allowed_attributes = %w(name image)
    error_hash = { "name_error" => "Header 'name' is missing or written in incorrect postition or not spelled correctly","image_error" => "Header 'image' is missing or written in incorrect position or not spelled correctly" ,"both_header" => "Both Headers are missing or written in incorrect postition or not spelled correctly","empty_file" => "CSV file is empty","unexpected_header" => "Headers more than what is expected","unexpected_data" => "Data is more than what is expected" ,"invalid_name" => "In Row no #{row_num} : Name should contain letters or digits only!","invalid_image" => "In Row no #{row_num} : Image URL is incorrect","missing_name" => "In Row no #{row_num} : Name is missing!", "missing_image" => "In Row no #{row_num} : Image URL is missing!","missing_content" => "Content is missing"}
    @headers = CSV.open(@file,'r') { |csv| csv.first } #To find first row of csv file i.e. header
    # check if headers are valid
    if @headers && !@headers.empty? # check if headers are present
      @headers = CSV.read(@file).flatten
      if CSV.read(@file).count == 2 || CSV.read(@file).count > 2
        count = allowed_attributes.count - @headers.count
        if count > 0
          #in this case either name is missing or image is missing or both
          if allowed_attributes[0].downcase != @headers[0].try(:downcase) && allowed_attributes[1].downcase != @headers[1].try(:downcase)
              @errors << error_hash['both_header']
          end
          if allowed_attributes[0].downcase != @headers[0].try(:downcase)
              @errors << error_hash['name_error']
          end
          if allowed_attributes[1].downcase != @headers[1].try(:downcase)
              @errors << error_hash['image_error']
          end
        end
        if count < 0
          #in this case we will check if header data is proper or not
          if allowed_attributes[0].downcase != @headers[0].try(:downcase)
            @errors << error_hash['name_error']
          end
          if allowed_attributes[1].downcase != @headers[1].try(:downcase)
            @errors << error_hash['image_error']
          end
        end
      elsif CSV.read(@file).count == 1 #only one row exists
        count = allowed_attributes.count - @headers.count
        if count == 0
          if allowed_attributes[0].downcase != @headers[0].try(:downcase) && allowed_attributes[1].downcase != @headers[1].try(:downcase)
              @errors << error_hash['both_header']
          end
          if allowed_attributes[0].downcase != @headers[0].try(:downcase)
              @errors << error_hash['name_error']
          end
          if allowed_attributes[1].downcase != @headers[1].try(:downcase)
              @errors << error_hash['image_error']
          end
        end
        if count > 0 #less than what is expected
          if @headers[0] && @headers[1] && allowed_attributes[0].downcase != @headers[0].try(:downcase) && allowed_attributes[1].downcase != @headers[1].try(:downcase)
                @errors << error_hash['both_header']
          end
          if @headers[0] && allowed_attributes[0].downcase != @headers[0].try(:downcase)
              @errors << error_hash['name_error']
          end
          if @headers[0] && allowed_attributes[1].downcase != @headers[0].try(:downcase)
              @errors << error_hash['image_error']
          end
        end
        if count < 0 #more than what is expected
            @errors << error_hash['unexpected_header']
        end
      elsif CSV.read(@file).count == 0 #no row exists
        @errors << error_hash['empty_file']
      else
        @errors << error_hash['empty_file']
      end
    else
      @errors << error_hash['empty_file']
    end
    @errors
  end

  def all_letters_or_digits(str)
    str[/[a-zA-Z0-9]+/]  == str
  end

  def validate_name(row, row_num)
    unless row[0].empty?
      if !all_letters_or_digits(row[0])
        @errors << error_hash['invalid_name']
      end
    else
      @errors << error_hash['missing_name']
    end
  end

  def validate_url?(string)
     Rails.logger.info(string)
    if string =~ URI::regexp
      true
    else
      false
    end
  end

  def validate_image(row, row_num)
    unless row[1].empty?
      if validate_url?(row[1])
        return true
      else
        @errors << error_hash['invalid_image']
        return false
      end
    else
      @errors << error_hash['missing_image']
    end
  end

  def check_value(row,row_num)
    unless row[0].empty?
       if !all_letters_or_digits(row[0])
          @errors << error_hash['invalid_name']
        end
        if !validate_url?(row[0])
          @errors << error_hash['invalid_image']
        end
    end
  end

  #validation of data in a csv file
  def validate_csv_data(row,index)
    if row.any? && !row.empty?
      row = row.first.split(",")
      if @row.length  == 2
        if row.length == 1 # if true that means either name data is missing or image data is missing
          check_value(row,index+1)
        end
        if row.length == 2
          validate_name(row,index+1)
          validate_image(row,index+1)
        end
        if row.length > 2
          @errors << error_hash['unexpected_data']
        end
      elsif @row.length  > 2
        if row.length == 1 # if true that means either name data is missing or image data is missing
          check_value(row,index+1)
        end
        if row.length == 2
          validate_name(row,index+1)
          validate_image(row,index+1)
        end
        if row.length > 2
          @errors << error_hash['unexpected_data']
        end
      else
        @errors << error_hash['missing_content']
      end
    else
      @errors << error_hash['missing_content']
    end
  end
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/views/galleries/_csv_form.html.erb
<%= form_tag import_user_galleries_path, remote: true, multipart: true, id: 'csv_form' do %>
  <% if @errors.present? %>
    <div class="alert alert-danger" style="width:100%"><%= alert %>
        <% @errors.each do |msg| %>
          <%= msg %>
        <% end %>
    </div>
  <% end %>
  <div class="form-group">
    <%= label_tag :file, "Upload File", class: "form-label" %>
    <%= file_field_tag :file, class: "form-control" %>
  </div>
  <%= submit_tag "Import CSV", class: 'btn btn-primary' %>
<% end %>

<script>
  $(document).ready(function() {
    $("#csv_form").validate({
      debug: true,
      rules: {
        "file": {required: true, accept: "text/csv"}
      }
    });

    $('form').submit(function() {  
    //var valuesToSubmit = $(this).serialize();
      $.ajax({
              type:'GET',
              datatype:'json',
              url: '/galleries/get_image_count',
              success: function(response) {
                $("#loader-div").hide();
                data = "Total Count "+response.data;
                $('span.count').html(data).css('color', 'green');
              },
      });
    });
  });
</script>

app/views/galleries/_edit.html.erb
<%= form_for [@user, @gallery], remote: true, html: { multipart: true } do |f| %>

  <% if @gallery.errors.any? %>
    <div class="panel panel-warning errors">
      <div class="panel-heading">
        <h5><i class="glyphicon glyphicon-exclamation-sign"></i> Errors Found.Could not save it.</h5>
      </div>

      <ul class="panel-body">
        <% @gallery.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <%= f.submit 'Update', class: 'btn btn-primary' %>
<% end %>

<script>
  $(document).ready(function () {
    var user_id = <%=j @user.id.to_s %>;
    var gall_id = <%=j @gallery.id.to_s %>;
    $(".edit_gallery").validate({
      debug: true,
      rules: {
        "gallery[name]": {required: true, remote:"/users/"+user_id+"/galleries/"+gall_id+"/check_name"}
      },
      messages: {
        "gallery[name]": "Image Name already exists"
      }
    });
  });
</script>

app/views/galleries/_form.html.erb
<%= form_for [@user, @gallery], remote: true, html: { multipart: true } do |f| %>
  <% if @gallery.errors.any? %>
    <%= render 'shared/errors', object: @gallery  %>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: 'form-control'%>
  </div>

  <%= f.submit 'Upload', class: 'btn btn-primary' %>
<% end %>

<script>
  $(document).ready(function() {
    var user_id = <%=j @user.id.to_s %>;
    var gall_id = <%=j @gallery.id.to_s %>;
    $("#new_gallery").validate({
      debug: true,
      rules: {
        "gallery[name]": {required: true, remote:"/users/"+user_id+"/galleries/"+gall_id+"/check_name"},
        "gallery[image]": {required: true, accept: "image/*"}
      },
      messages: {
        "gallery[name]": "Image Name already exists"
      }
    });

    $('form').submit(function() {  
      $.ajax({
              type:'GET',
              datatype:'json',
              url: '/galleries/get_image_count',
              success: function(response) {
                $("#loader-div").hide();
                data = "Total Count "+response.data;
                $('span.count').html(data).css('color', 'green');
              },
      });
    });
  });
</script>

app/views/galleries/_gallery.html.erb
<% galleries.each do |gallery| %>
  <div class = "photo-box">
    <div class="row">
      <div class="col-xs-4"></div>
      <div class="col-xs-4" style="display:inline; background-color:#E0E0E0;width:33%">
        <%= div_for gallery do %>
          <div class="panel">
            <%= image_tag gallery.image.url(:large) %><br/>
            <%= link_to "#{gallery.name}", edit_user_gallery_path(@user, gallery), id: "gall_#{gallery.id}",  class: "gallery_name_link"  ,remote: true %><br/>

           </div>
        <% end %>
      </div>
      <div class="col-xs-4"></div>
    </div>
  </div>
<% end %>

<div class="container">
  <div class="row">
    <div class="col-xs-4"></div>
    <div class="col-xs-4">
      <div class="pagination">
        <%= paginate @galleries %>
      </div>
    </div>
    <div class="col-xs-4"></div>
  </div>
</div>


<script>
$(document).ready(function () {
  $('a.gallery_name_link').click(function(e) {
    var id = $(this).attr('id');
    $('.col-xs-4').find( "a:hidden" ).not('gall_'+id).show();
  });
});
</script>

app/views/galleries/create.js.erb
$('form').hide();
$('.new-img-btn').show();
$('.gallery-box').html("<%= escape_javascript(render partial: 'gallery', locals: {galleries: @galleries}) %>");

app/views/galleries/edit.js.erb
$('form').hide();
$('div#<%= dom_id(@gallery) %>').find('.panel').append('<%= j render("edit") %>');
$('div#<%= dom_id(@gallery) %>').find('.panel').find('a').hide();

app/views/galleries/import.js.erb
$('form').hide();
$('.new-csv-btn').after('<%= j render("csv_form") %>');

app/views/galleries/import_csv_form.js.erb
$('form').hide();
$('.new-csv-btn').after('<%= j render("csv_form") %>');
$('.new-img-btn').hide();
$('.new-csv-btn').hide();

app/views/galleries/index.html.erb
<div class = "content-box">
  <div class='container' style="width:60%;">
    <div class="row">
      <div class="col-xs-4">
        <%= link_to "Upload New Image", new_user_gallery_path, remote: true, class: "new-img-btn btn btn-primary" %>
        <%= link_to "Upload CSV", import_csv_form_user_galleries_path, remote: true, class: "new-csv-btn btn btn-primary" %> 
        <div id = "loader-div" style="color: #ffd700;">
          Total Count <%= image_tag("loader.gif", height: '90', width: '90') %>
        </div>
      </div>
    </div>
  </div>
  <br/>
  <div class="container gallery-box">
    <%= render 'galleries/gallery', galleries: @galleries %>
  </div>
</div>

app/views/galleries/new.js.erb
$('form').hide();
$('.new-img-btn').after('<%= j render("form") %>');
$('.new-csv-btn').hide();
$('.new-img-btn').hide();

app/views/galleries/update.js.erb
$('form').hide();
$('div#<%= dom_id(@gallery) %>').find('a').text("<%= @gallery.name %>").show();