config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'contacts/new'

  get 'contacts/create'

  get 'contacts/create'
  get 'contacts/new'
  #get 'home/gallery'
  
  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config
  root to: 'home#index'
  devise_for :users, controllers: {registrations: 'registrations'}
  resources "contacts", only: [:new, :create]
  resources :users do
    resources :galleries do
      collection do
        get :import_csv_form
        post :import
      end
    end
  end
  resources :users do
    resources :galleries do
      member do
        get :check_name
      end
    end
  end

  resources :galleries do
    collection do
      get :get_image_count
    end
  end
  
  namespace :api do
      namespace :v1 do
        resources :gallery_pictures, only: [] do
          collection do
            post :upload
          end
          member do
            get :retrieve
          end
        end
        resources :contacts, only: [] do
          collection do
            post :send_message
          end
        end
        resources :users, only: [] do
          collection do
            post :create_user
          end
        end
      end
  end

  match "*path", to: "api/v1/errors#routing", via: :all
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
end

app/views/layouts/_footer.html.erb
<div class = 'footer_box'>
	<footer>
		<div class="row">
			<div class="col-sm-4" style="width:20%;margin-left:38%;">
				<div class="footer-block text-center">
					<p class="copyright">
						©2017 Maropost Inc. All rights reserved. | 
						<ul class="list-inline footer-menu">
							<li><%= link_to 'Contact Us', new_contact_path %></li>
						</ul>
					</p>
				</div>
			</div>
		</div>
	</footer>
</div>

app/views/layouts/_header.html.erb
<div class= 'header_box'>
  <nav class="navbar navbar-inverse">
    <div id="navbar">
      <ul class="nav navbar-nav">
        <li><%= link_to 'About Us', root_path %></li>
      </ul>
      <ul class="nav navbar-nav">
        <li><%= link_to 'Contact Us', new_contact_path %></li>
      </ul>
      <ul class="nav navbar-nav">
        <li><%= link_to 'Gallery', user_galleries_path(current_user)%></li>
      </ul>
      <ul class="nav navbar-right">
        <li><%= link_to "LOG OUT", destroy_user_session_path, method: :delete %></li>
      </ul>
      <ul class="nav navbar-right">
        <li><%= link_to "Account Settings", edit_user_registration_path %></li>
      </ul>
    </div>
  </nav>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
	  <div class="alert alert-<%= key %>">
	    <a href="#" data-dismiss="alert" class="close">×</a>
	     <p> <%= value %> </p>
	   </div>
	<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Demo</title>
      <%= csrf_meta_tags %>
      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.17.0/jquery.validate.min.js' %>
      <%= javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.17.0/additional-methods.min.js' %>
  </head>

  <body>
    <div class = main_box>
      <div class = "error-box">
        <% if user_signed_in? %>
          </div>
          <%= render 'layouts/header' %>
          <div class='notice'>
            <% if notice %>
              <p style="width:20%;"class="alert alert-success text-center"><%= notice %></p>
            <% end %>
            <% if alert %>
              <p class="alert alert-danger text-center"><%= alert %></p>
            <% end %>
            <% if @errors %>
              <% @errors.each do |message| %>
                <%= message %>
              <% end %>
            <% end %>
          </div>
          <%= yield %>
          <%= render 'layouts/footer' %>
        <%else %>
          <%= render 'layouts/messages' %>
          </div>
          <%= yield %>
        <% end %>
      </div>
  </body>
</html>